mysite/HTML/urls.py
#!/usr/bin/env python3
#-*- coding:UTF-8 -*-

from django.urls import path
from . import views

app_name = 'HTML'
urlpatterns = [
    path('', views.HtmlView.as_view(), name='html'),
]

mysite/mysite/urls.py
# !/usr/bin/env python3
# -*- coding:UTF-8 -*-


"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    # path('polls/', include('polls.urls')),
    # path('uploads/', include('uploads.urls')),
    # HTML测试
    # path('html/', include('HTML.urls')),

    # 马哥实战测试
    # path('hello/', include('hello.urls')),
    path('user/', include('users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
#!/usr/bin/env python3
#-*- coding:UTF-8 -*-

from django.urls import path, re_path
from .views import *

app_name = 'users'
urlpatterns = [
    # path('useradd/', useradd, name='useradd'),
    # re_path('userdel/(?P<pk>[0-9]+)?/', userdel, name='userdel'),
    # re_path('useredit/(?P<pk>[0-9]+)?/', useredit, name='useredit'),
    # path('userlist/', userlist, name='userlist'),
    # 通用视图
    # path('index/', IndexView.as_view(), name='index'),
    # path('userlist/', UserListView.as_view(), name='userlist'),
    # DetailView
    # re_path('detail/(?P<pk>[0-9]+)?/', Detail.as_view(), name='detail' ),
    # CreateView
    # path('useradd/', UserAddView.as_view(), name='useradd'),
    # UpdateView
    # re_path('useredit/(?P<pk>[0-9]+)?/', UserUpdateView.as_view(), name='useredit'),
    # DeleteView
    # re_path('userdel/(?P<pk>[0-9]+)?/', UserDeleteView.as_view(), name='userdel'),

    # modelform
    # path('useradd/', UserFormAdd.as_view(), name='useradd'),
    # path('userlist/', UserFormList.as_view(), name='userlist'),
    # re_path('detail/(?P<pk>[0-9]+)?/', UserFormDetail.as_view(), name='detail' ),

    # jQuery版本
    # path('useradd/', UserFormAdd.as_view(), name='useradd'),
    # path('userlist/', UserFormList.as_view(), name='userlist'),
    # re_path('detail/(?P<pk>[0-9]+)?/', UserFormDetail.as_view(), name='detail' ),

    # 表单
    # path('form/', FormView.as_view(), name='form'),
    # path('modelform/', ModelFormView.as_view(), name='modelform'),

    # 前端测试
    # path('css/', CssView.as_view(), name='css'),
    # path('js/', JssView.as_view(), name='jss'),
    # path('jq/', JqView.as_view(), name='jq'),
    # path('bs/', BsView.as_view(), name='bs'),

    # 全新用户系统(前端美化)
    # 老师版本
    path('userlist/', UserListView.as_view(), name='userlist'),
    path('useradd/', UserAddView.as_view(), name='useradd'),
    re_path('useredit/(?P<pk>[0-9]+)?/', UserEditView.as_view(), name='useredit'),
    re_path('userdel/(?P<pk>[0-9]+)?/', UserDelView.as_view(), name='userdel'),

    # 自己改版
    # path('useradd/', UserFormAddView.as_view(), name='useradd'),
    # path('userlist/', UserFormListView.as_view(), name='userlist'),
    # re_path('useredit/(?P<pk>[0-9]+)?/', UserFormEditView.as_view(), name='useredit'),
    # re_path('userdel/(?P<pk>[0-9]+)?/', UserFormDelView.as_view(), name='userdel'),
]

mysite/templates/_paginator.html
<ul class="pagination m-b-5" style="float: right">
    {% if page_obj.has_previous %}
        <li><a href="?page=1">首页</a></li>
        <li><a href="?{{ page_obj.previous_page_number.querystring }}" aria-label="上一页">上一页</a></li>
    {% else %}
        <li><a class="disabled" href="?page=1">首页</a></li>
        <li><a class="disabled">上一页</a></li>
    {% endif %}
    {% for page in page_obj.pages %}
         {% if page %}
            {% ifequal page page_obj.number %}
                <li class="active"><a class="">{{ page }}</a></li>
            {% else %}
                <li><a class="" href="?{{ page.querystring }}">{{ page }}</a></li>
            {% endifequal %}
        {% else %}
             <li><a class="" href="javascript:void(0)">...</a></li>
        {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
        <li><a class="" href="?{{ page_obj.next_page_number.querystring }}">下一页</a></li>
        <li><a class="" href="?page={{ page_obj.paginator.num_pages }}">尾页</a></li>
    {% else %}
        <li><a class="disabled">下一页</a></li>
        <li><a class="disabled">尾页</a></li>
    {% endif %}
</ul>

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
    {% block head %}NetDevOps{% endblock %}
    </title>
</head>

<body>
    {#每个页面都有一个标题且样式基本不会变，可以抽象出来，变的标题内容做成变量#}
    <p style="color: green">
        {% block title %} 用户列表 {% endblock %}
    </p>

    {#页面的内容都是变化的，做成变量即可#}
    {% block content %}
        这是模板的内容
    {% endblock %}

    {% block js %}
    {% endblock %}

    <p style="color: red">版权所有©点滴技术</p>
</body>
</html>

mysite/templates/base1.html
<!DOCTYPE html>
{% load  static %}
<html lang="en">
    
<head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <!-- 页面标签 -->
        <title>
            {% block title %}自动化运维平台{% endblock %}
        </title>

        <!-- 加载CSS样式 -->
        <!-- Bootstrap core CSS -->
        <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">
        <link href="{% static "css/bootstrap-reset.css" %}" rel="stylesheet">

        <!--Animation css-->
        <link href="{% static "css/animate.css" %}" rel="stylesheet">

        <!--Icon-fonts css-->
        <link href="{% static "assets/font-awesome/css/font-awesome.css" %}" rel="stylesheet" />
        <link href="{% static "assets/ionicon/css/ionicons.min.css" %}" rel="stylesheet" />

        <!--Morris Chart CSS -->
        <link rel="stylesheet" href="{% static "assets/morris/morris.css" %}">

        <!-- sweet alerts -->
{#        <link href="{% static "assets/sweet-alert/sweet-alert.min.css" %}" rel="stylesheet">#}

        <!-- Custom styles for this template -->
        <link href="{% static "css/style.css"  %}" rel="stylesheet">
        <link href="{% static "css/helper.css" %}" rel="stylesheet">

        <!-- Plugin Css-->
        <link rel="stylesheet" href="{% static "assets/magnific-popup/magnific-popup.css"%}" />
        <link rel="stylesheet" href="{% static "assets/jquery-datatables-editable/datatables.css"%}" />

        <!-- Custom styles for this template -->
        <link rel="stylesheet" href="{% static "css/style.css" %}">
        <link rel="stylesheet" href="{% static "css/helper.css" %}">

        {% block css %}{% endblock %}
</head>

    <body>
        <!-- Aside Start-->
        <aside class="left-panel">
            <!-- brand -->
            <div class="logo">
                <a href="{% url 'index' %}" class="logo-expanded">
                    <i class="ion-social-buffer"></i>
                    <span class="nav-label">自动化运维平台</span>
                </a>
            </div><!-- / brand -->

            <!-- Navbar Start 导航栏 -->
            <nav class="navigation">
                <ul class="list-unstyled">
                    <li class="active"><a href="#"><i class="ion-home"></i> <span class="nav-label">仪表盘</span></a></li>
                    <li class="has-submenu"><a href="#"><i class="ion-android-social-user"></i> <span class="nav-label">用户权限管理</span></a>
                <ul class="list-unstyled">
                    <li class="users"><a href="{% url 'users:userlist' %}">用户管理</a></li>
                    <li class="roles"><a href="#">角色管理</a></li>
                    <li class="permissions"><a href="#">权限管理</a></li>
                </ul>
                    </li>
                </ul>
            </nav><!-- Navbar Ends -->
        </aside><!-- Aside Ends-->

        <!--Main Content Start -->
        <section class="content">
            
            <!-- Header -->
            <header class="top-head container-fluid">
                <!-- 左上角收缩 导航栏 -->
                <button type="button" class="navbar-toggle pull-left">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <nav class=" navbar-default" role="navigation">
                    <!-- Right navbar -->
                    <ul class="nav navbar-nav navbar-right top-menu top-right-menu">
                        <!-- user login dropdown start-->
                        <li class="dropdown text-center">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <img alt="" src="{% static "img/avatar-2.jpg" %}" class="img-circle profile-img thumb-sm">
                                <span class="username"> admin </span> <span class="caret"></span>
                            </a>
                            <ul class="dropdown-menu pro-menu fadeInUp animated" tabindex="5003" style="overflow: hidden; outline: none;">
                                <li><a href="#"><i class="fa fa-edit"></i> 修改密码</a></li>
                                <li><a href="#"><i class="fa fa-sign-out"></i> 退出 </a></li>
                            </ul>
                        </li>
                        <!-- user login dropdown end -->       
                    </ul>
                    <!-- End right navbar -->
                </nav>
                
            </header>
            <!-- Header Ends -->
            <!-- 以上就是每一个页面共用的部分，即母版 -->

            <!-- Page Content Start -->
            <!-- ================== -->
            <!-- 以下就是每一个页面自定义内容的部分 -->
            <div class="wraper container-fluid">
                <div class="page-title"> 
                    <h3 class="title"> {% block page-title %} {% endblock %} </h3>
                </div>

                {% block page-content %} {% endblock %}

            </div>
            <!-- Page Content Ends -->
            <!-- ================== -->

            <!-- 页脚 Footer Start -->
            <footer class="footer">
        		2021©自动化运维平台
            </footer>
            <!-- 页脚 Footer Ends -->

        </section>
        <!-- Main Content Ends -->
        <script src="{% static 'js/jquery.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/wow.min.js' %}"></script>
        <script src="{% static 'js/pace.min.js' %}"></script>
        <!--控制菜单栏点击显示子菜单-->
        <script src="{% static 'js/jquery.app.js' %}"></script>
        <!--子菜单点击时，不收缩-->
        <script src="{% static 'js/jquery.nicescroll.js' %}" ></script>

        {% block js %}{% endblock %}

    </body>
</html>

mysite/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>首页</title>
</head>
<body>
    <H1 style="color: red">This is Django.</H1>
</body>
</html>

mysite/templates/index1.html
{% extends 'base1.html' %}

{% load static %}

{% block head %} 首页 {% endblock %}

mysite/templates/jump.html
{% extends 'base.html' %}

{% block content %}
    {% if code == 0 %}
        <h1> {{ result }} </h1>
    {% else %}
        <h1> 操作失败:</h1>
        <h3 style="color: red">{{ result }}</h3>
    {% endif %}
{% endblock %}

{% block js %}
    <script type="text/javascript" src="/static/js/jquery-3.6.0.min.js"></script>

    <script>
        let status = {{ code }};
        let next_url = "{{ next_url|safe }}";
        let timejump = 1500;
        $(function () {
            if (status != 0){
                timejump = 5000
            }
            setTimeout(function () {
                window.location.href = next_url;
            }, timejump)
        })
    </script>
{% endblock %}