mysite/HTML/urls.py
#!/usr/bin/env python3
#-*- coding:UTF-8 -*-

from django.urls import path
from . import views

app_name = 'HTML'
urlpatterns = [
    path('', views.HtmlView.as_view(), name='html'),
]

mysite/mysite/urls.py
# !/usr/bin/env python3
# -*- coding:UTF-8 -*-


"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    # path('polls/', include('polls.urls')),
    # path('uploads/', include('uploads.urls')),
    # HTML测试
    # path('html/', include('HTML.urls')),

    # 马哥实战测试
    # path('hello/', include('hello.urls')),
    path('user/', include('users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/users/urls.py
#!/usr/bin/env python3
#-*- coding:UTF-8 -*-

from django.urls import path, re_path
from .views import *

app_name = 'users'
urlpatterns = [
    # path('useradd/', useradd, name='useradd'),
    # re_path('userdel/(?P<pk>[0-9]+)?/', userdel, name='userdel'),
    # re_path('useredit/(?P<pk>[0-9]+)?/', useredit, name='useredit'),
    # path('userlist/', userlist, name='userlist'),
    # 通用视图
    # path('index/', IndexView.as_view(), name='index'),
    # path('userlist/', UserListView.as_view(), name='userlist'),
    # DetailView
    # re_path('detail/(?P<pk>[0-9]+)?/', Detail.as_view(), name='detail' ),
    # CreateView
    # path('useradd/', UserAddView.as_view(), name='useradd'),
    # UpdateView
    # re_path('useredit/(?P<pk>[0-9]+)?/', UserUpdateView.as_view(), name='useredit'),
    # DeleteView
    # re_path('userdel/(?P<pk>[0-9]+)?/', UserDeleteView.as_view(), name='userdel'),

    # modelform
    # path('useradd/', UserFormAdd.as_view(), name='useradd'),
    # path('userlist/', UserFormList.as_view(), name='userlist'),
    # re_path('detail/(?P<pk>[0-9]+)?/', UserFormDetail.as_view(), name='detail' ),

    # jQuery版本
    # path('useradd/', UserFormAdd.as_view(), name='useradd'),
    # path('userlist/', UserFormList.as_view(), name='userlist'),
    # re_path('detail/(?P<pk>[0-9]+)?/', UserFormDetail.as_view(), name='detail' ),

    # 表单
    # path('form/', FormView.as_view(), name='form'),
    # path('modelform/', ModelFormView.as_view(), name='modelform'),

    # 前端测试
    # path('css/', CssView.as_view(), name='css'),
    # path('js/', JssView.as_view(), name='jss'),
    # path('jq/', JqView.as_view(), name='jq'),
    # path('bs/', BsView.as_view(), name='bs'),

    # 全新用户系统(前端美化)
    # 老师版本
    path('userlist/', UserListView.as_view(), name='userlist'),
    path('useradd/', UserAddView.as_view(), name='useradd'),
    re_path('useredit/(?P<pk>[0-9]+)?/', UserEditView.as_view(), name='useredit'),
    re_path('userdel/(?P<pk>[0-9]+)?/', UserDelView.as_view(), name='userdel'),

    # 自己改版
    # path('useradd/', UserFormAddView.as_view(), name='useradd'),
    # path('userlist/', UserFormListView.as_view(), name='userlist'),
    # re_path('useredit/(?P<pk>[0-9]+)?/', UserFormEditView.as_view(), name='useredit'),
    # re_path('userdel/(?P<pk>[0-9]+)?/', UserFormDelView.as_view(), name='userdel'),
]

mysite/users/models.py
#!/usr/bin/env python3
#-*- coding:UTF-8 -*-

from django.db import models
from django.contrib.auth.models import AbstractUser


# class User(models.Model):
#     SEX = ((1, '男'),
#            (2, '女'))
#     name = models.CharField(max_length=10, help_text='用户名')
#     phone = models.CharField(max_length=11, default='13800000001', help_text='手机')
#     password = models.CharField(max_length=64, help_text='密码')
#     sex = models.IntegerField(choices=SEX, null=True, blank=True)
#
#     def __str__(self):
#         return self.name

class Userprofile(AbstractUser):
    SEX_CHOICE = (
        (0, '男'),
        (1, '女'),
    )
    cn_name = models.CharField('中文名', max_length=128)
    phone = models.CharField('手机', max_length=11, null=True, blank=True)
    sex = models.IntegerField(choices=SEX_CHOICE, null=True, blank=True)


    class Meta:
        verbose_name = '用户信息'

    def __str__(self):
        return self.username

mysite/users/views.py
# !/usr/bin/env python3
# -*- coding:UTF-8 -*-

import traceback

from django.contrib.auth.hashers import make_password
from django.db.models import Q
from django.http import JsonResponse, QueryDict
from django.shortcuts import render,reverse,HttpResponse, HttpResponseRedirect, get_object_or_404, Http404
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView,CreateView,UpdateView,DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from pure_pagination.mixins import PaginationMixin
# from .models import User
from .form import UserForm
# from .form import UsersForm, UserModelForm, UserUpdateModelForm
from .form import UsersForm, UserModelForm
from django.conf import settings
from .models import Userprofile
from django.contrib.auth import get_user_model

import logging

log = logging.getLogger('devops')

User = get_user_model()

"""FBV(Function Basic View)"""
# def useradd(request):
#     """
#     添加用户
#     """
#     # print(request.method)
#     msg = {}
#     if request.method == 'POST':
#         try:
#             data = request.POST.dict()
#             User.objects.get_or_create(**data)
#             msg = {'code': 0, 'res': '创建用户成功.'}
#             log.info('添加用户成功.')
#         except:
#             # msg = {'code':1, "res":"创建用户失败: %s" % traceback.format_exc() }
#             msg = {'code':1, "res":"创建用户失败"}
#             log.error("创建用户失败: %s" % traceback.format_exc())
#
#     return render(request,'users/useradd.html', {'msg':msg})

# def userdel(request, **kwargs):
#     """
#     删除用户
#     """
#     pk = kwargs.get('pk', '')
#     try:
#         user = User.objects.get(id=pk)
#     except User.DoesNotExist:
#         raise Http404
#
#     msg = {}
#     if request.method == 'POST':
#         try:
#             User.objects.filter(id=pk).delete()
#             msg = {'code': 0, 'res': '删除用户成功.'}
#         except:
#             msg = {'code': 1, "res": "删除用户失败: %s" % traceback.format_exc()}
#
#     return render(request, 'users/userdel.html', {'pk':pk, 'user':user,'msg':msg})

# def useredit(request, **kwargs):
#     """
#     编辑用户
#     """
#     pk = kwargs.get('pk', '')
#     user = get_object_or_404(User, pk=pk)
#     msg = {}
#     if request.method == 'POST':
#         try:
#             data = request.POST.dict()
#             User.objects.filter(id=pk).update(**data)
#             msg = {'code': 0, 'res': '更新用户成功.'}
#         except:
#             msg = {'code': 1, "res": "更新用户失败: %s" % traceback.format_exc()}
#
#     return render(request, 'users/useredit.html', {'user':user, 'msg':msg})
#
# def userlist(request):
#     """
#     查看用户
#     """
#     keyword = request.GET.get('keyword', '')
#     userlist = User.objects.all()
#     if keyword:
#         userlist = User.objects.filter(name__icontains=keyword)
#     return render(request, 'users/userlist.html', {'userlist':userlist, 'keyword':keyword})


"""通用视图"""
# class IndexView(View):
#     def get(self, request):
#         return HttpResponse('this is get method.')
#     def post(self, request):
#         return HttpResponse('this is post method.')
#     def put(self, request):
#         return HttpResponse('this is put method.')
#     def delete(self, request):
#         return HttpResponse('this is delete method.')

# class UserListView(View):
#     def get(self, request):
#         keyword = request.GET.get('keyword', '')
#         if keyword:
#             userlist = User.objects.filter(name__icontains=keyword)
#         userlist = User.objects.all()
#         return render(request, 'users/userlist.html', {'userlist':userlist, 'keyword':keyword}

# class UserListView(TemplateView):
#     template_name = 'users/userlist.html'
#
#     def get_context_data(self, **kwargs):
#         context = super(UserListView, self).get_context_data(**kwargs)
#         print(kwargs)
#         context['userlist'] =  User.objects.all()
#         print(context)
#         return context

# class UserListView(ListView):
#     template_name = 'users/userlist.html'
#     model = User
#     context_object_name = 'userlist'
#     keyword = ''

#     def get_queryset(self):
#         """
#         过滤数据传给前端渲染。
#         """
#         # 拿到所有数据
#         queryset = super(UserListView, self).get_queryset()
#         # print('所有数据结果:', queryset)
#         self.keyword = self.request.GET.get('keyword', '')
#         # print('关键字:', self.keyword)
#         # 搜索查询,过滤数据
#         if self.keyword:
#             # 过滤name
#             queryset = queryset.filter(name__icontains=self.keyword)
#             # print('过滤后的数据:', queryset)
#         return queryset
#
#     def get_context_data(self, *, object_list=None, **kwargs):
#         """
#         搜索后返回过滤数据及搜索框内的关键字
#         """
#         context = super(UserListView, self).get_context_data(**kwargs)
#         context['keyword'] = self.keyword
#         # print('context结果:', context)
#         return context


# class Detail(DetailView):
#     template_name = 'users/userdetail.html'
#     model = User
#     context_object_name = 'user'


# class UserAddView(SuccessMessageMixin, CreateView):
#     template_name = 'users/useradd.html'
#     model = User
#     fields = {'name', 'password', 'sex'}
#     success_message = "%(name)s was created successfuly"
#
#     def get_success_url(self):
#         # print(self.request.POST)
#         if '_addanother' in self.request.POST:
#             return reverse('users:useradd')
#         return reverse('users:userlist')
#
#     def form_valid(self, form):
#     #     print(form.errors)
#         print('~~~~~~~~~~~~~~~')
#         return HttpResponseRedirect(self.get_success_url())
#
#     # def form_invalid(self, form):
#         # print(form)
#         # return self.render_to_response(self.get_context_data(form=form))
#
#
#     # def get_context_data(self, **kwargs):
#     #     context = super(UserAddView, self).get_context_data(**kwargs)
#     #     users = User.objects.all()
#     #     context['users'] = users
#     #     return context


# class UserUpdateView(SuccessMessageMixin, UpdateView):
#     template_name = 'users/useredit.html'
#     model = User
#     fields = {'name', 'password', 'sex'}
#     success_message = "%(name)s was update successfuly"
#
#     def get_success_url(self):
#         print(self.kwargs)
#         return reverse('users:detail', kwargs={'pk':self.kwargs['pk']})


# class UserDeleteView(DeleteView):
#     template_name = 'users/userdel.html'
#     model = User
#
#     def get_success_url(self):
#         return reverse('users:userlist')


# 原生表单，简介版本
# class FormView(View):
#     def get(self, request):
#         form = UsersForm()
#         # print(form)
#         return render(request, 'users/form.html', {'form':form})
#
#     def post(self, request):
#         form = UsersForm(request.POST)
#         if form.is_valid():
#             print(form.cleaned_data)
#             name = form.cleaned_data['name']
#             print(name)
#         return render(request, 'users/form.html', {'form':form})


# class ModelFormView(View):
#     def get(self, request):
#         return render(request, 'users/useradd.html')
#
#     def post(self, request):
#         form = UserModelForm(request.POST)
#         if form.is_valid():
#             print(form.cleaned_data)
#             name = form.cleaned_data['name']
#             print(name)
#         return render(request, 'users/useradd.html', {'form':form})

"""modelform"""
# class UserFormAdd(TemplateView):
#     """
#     添加用户
#     """
#     template_name = 'users/user_form.html'


# class UserFormList(ListView):
#     """
#     1、用户列表：支持搜索
#     2、用户添加：通过ModelForm验证
#     """
#     model = User
#     template_name = 'users/userform_list.html'
#     context_object_name = 'userlist'
#     keyword = ''
#
#     def get_queryset(self):
#         # 获取所有数据
#         queryset = super(UserFormList, self).get_queryset()
#         # print(1, queryset)
#         # 获取搜索框关键字
#         self.keyword = self.request.GET.get('keyword', '').strip()
#         if self.keyword:
#             # Q的"|"表示或，“&”表示与
#             queryset = queryset.filter(Q(name__icontains=self.keyword)|
#                                        Q(phone__icontains=self.keyword))
#             # print(2, queryset)
#         # 返回搜后后过滤的数据给context
#         return queryset
#
#     def get_context_data(self, **kwargs):
#         """
#         增加搜索关键字，一起传到前端
#         """
#         context = super(UserFormList, self).get_context_data(**kwargs)
#         # print(3, context)
#         context['keyword'] = self.keyword
#         # print(4, context)
#         return context
#
#     def post(self, request):
#         userform = UserModelForm(request.POST)
#         if userform.is_valid():
#             try:
#                 print(userform.cleaned_data)
#                 data = userform.cleaned_data
#                 self.model.objects.create(**data)
#                 # userform.save()
#                 res = {'code':0, 'result':'添加用户成功'}
#
#             except:
#                 res = {'code': 1, 'result': '添加用户失败'}
#                 log.error('添加用户失败%s' % traceback.format_exc())
#         else:
#             print(userform.errors)
#             print(userform.errors.as_json())
#             res = {'code': 1, 'result': userform.errors}
#
#         return render(request, settings.JUMP_PAGE, {'res':res})


# class UserFormDetail(DetailView):
#     """
#     1、用户更新
#     2、用户删除
#     """
#     template_name = 'users/userform_detail.html'
#     model = User
#     context_object_name = 'user'
#
#     def post(self, request, **kwargs):
#         keyword = kwargs.get('pk', '')
#         user = self.model.objects.get(id=keyword)
#         # print(user)
#         userform = UserUpdateModelForm(request.POST, instance=user)
#         # print(userform)
#         if userform.is_valid():
#             # 方法1： 原始的方法
#             # data = request.POST.dict()
#             # data.pop('confirm_password')

mysite/users/templates/users/bs.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <title>bootstrap测试</title>

{#    引入bootstrap的CSS样式#}
{#    <link href="/mysite/static/css/bootstrap.min.css" rel="stylesheet">#}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css">
{#    引入datatables#}
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.25/css/jquery.dataTables.css">
{#    引入Font Awesome#}
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

</head>

<body>


<button id="Btn" type="button" class="btn btn-primary">Primary</button>





{#引入jQuery#}
<script src="/mysite/static/js/jquery-3.6.0.js"></script>
{#引入bootstrap的js样式#}
{#<script src="/mysite/static/js/bootstrap.bundle.min.js"></script>#}
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js"></script>
{#引入bootstrap#}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"></script>
{#引入sweetalert#}
{#<script src="https://cdn.bootcss.com/sweetalert/1.1.3/sweetalert.min.js"></script>#}
<script src="{% static "js/sweetalert.min.js" %}"></script>
{#引入datatables#}
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.25/js/jquery.dataTables.js"></script>

{#<script>#}
{#    $(document).ready(function () {#}
{#        $("#table_id").dataTable();#}
{#    })#}
{#</script>#}

<script>
    $("#Btn").click(function () {
        swal("Good job!", "You clicked the button!", "success");
    })
</script>

{#<script>#}
{#    $(function () {#}
{#        $("#modalbtn").click(function () {#}
{#            $("#mymodal").modal("toggle");#}
{#        });#}
{#    });#}
{#</script>#}


</body>

</html>

mysite/users/templates/users/css.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CSS 测试</title>

{#    ID选择器#}
    <style type="text/css">
        #red {color: red}
        #green {color: green}
    </style>
{#    类选择器#}
    <style type="text/css">
        .center {text-align: center}
    </style>
{#    多种选择器混用#}
    <style>
        .list h1{
            color: #CC3434;
            background: #e8e8e8;
        }
        #yellow h2{
            color: yellowgreen;
            background: #e8e8e8;
        }
    </style>
{#    属性选择器#}
    <style type="text/css">
        [title] {
            color: red;
        }
    </style>
{#    元素选择器#}
    <style>
        h4 {
            color: red;
        }
    </style>

{#    引用外部bootstrap的cdn方式#}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css">
{#    引用本地方式#}
    <link rel="stylesheet" href="/static/css/mystyle.css">

</head>
<body>
    <p id="red">这是红色的段落.</p>
    <p id="green">这是绿色的段落.</p>

    <h1 class="center">The text is center.</h1>

    <div class="list">
        <h1>我使用h1的样式</h1>
    </div>

    <div id="yellow">
        <h2>我使用h2的样式</h2>
    </div>

    <h3 title="h3">我使用属性选择器.</h3>

    <h4>我使用元素选择器.</h4>


    <p class="text-muted">
        <a href="#" class="text-reset">我使用CDN样式.</a>
    </p>
    <h5>我使用h5样式.</h5>



</body>
</html>

mysite/users/templates/users/useredit.html
{% extends 'base.html' %}

{% block head %} 编辑用户 {% endblock %}

{% block title %} 编辑用户 {% endblock %}

{% block content %}
    {% if msg.code == 0 %}
        <p style="color: green">{{ msg.res }}</p>
    {% else %}
        <p style="color: red">{{ msg.res }}</p>
    {% endif %}

    <form style="border: #19865C" action="{% url 'users:useredit' user.id %}" method="post" enctype="application/x-www-form-urlencoded">
        姓名：<input type="text" name="name"  value="{{ user.name }}" placeholder="姓名">
        <br><br>
        密码：<input type="password" name="password"  value="{{ user.password }}" placeholder="密码">
        <br><br>
        {% if user.sex == 1 %}
        <input type="radio" name="sex" value="1" checked>男<input type="radio" name="sex" value="2">女
         {% else %}
        <input type="radio" name="sex" value="1">男<input type="radio" name="sex" value="2" checked>女
        {% endif %}
        <br><br>
        <button type="reset">重置</button>
        <button type="submit">提交</button>
    </form>

{% endblock %}

mysite/users/templates/users/userlist.html
{% extends 'base1.html' %}
{% load static %}

{% block title %}
    用户列表
{% endblock %}

{% block page-title %}
    用户列表
{% endblock %}


{% block css %}
    <!-- sweet alerts -->
{#    <link href="{% static "assets/sweet-alert/sweet-alert.min.css"%}" rel="stylesheet">#}
    <link rel="stylesheet" href="{% static "assets/sweet-alert/sweetalert2.min.css"%}">
    <link rel="stylesheet" href="{% static "assets/sweet-alert/sweetalert2.css"%}">

{% endblock %}

{% block page-content %}
<div class="row">

    <div class="panel">
        <div class="panel-body">
            <!--添加及搜索行 start-->
            <div class="row">
                <!--添加按钮-->
{#                {% if perms.users.add_userprofile %}#}
                <div class="col-sm-6">
                    <div class="m-b-30">
                        <a href="{% url 'users:useradd' %}" type="button" class="btn btn-primary waves-effect waves-light">添加用户 <i class="fa fa-plus"></i></a>
                    </div>
                </div> <!--添加按钮 ends-->
{#                {% endif %}#}

                <!--搜索-->
                <div class="col-md-3" style="float: right">
                    <form class="form-horizontal" role="form">
                        <div class="input-group">
                            <input type="text"  name="keyword" class="form-control"  value="{{ keyword|default_if_none:'' }}" placeholder="请输入查询的关键字">
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-effect-ripple btn-primary">搜索</button>
                            </span>
                        </div>
                    </form>
                </div><!--搜索 ends-->

            </div><!--添加及搜索行 ends-->

            <!--表格 start-->
            <table class="table table-bordered table-striped">
                <thead>
                    <tr>
                        <th>UID</th>
                        <th>用户名</th>
                        <th>管理员</th>
                        <th>中文名</th>
                        <th>手机</th>
                        <th>性别</th>
                        <th>用户状态</th>
                        <th>上次登陆时间</th>
{#                        {% if perms.users.change_userprofile or perms.users.delete_userprofile %}#}
                        <th>操作</th>
{#                        {% endif %}#}
                    </tr>
                </thead>

                <tbody>
                {% for user in users %}
                <tr class="gradeA">
                    <td>{{ user.id }}</td>
                    <td>{{ user.username }}</td>
                    <td>{% if user.is_superuser == 1 %}超级管理员 {% else %} 普通用户 {% endif %}</td>
                    <td>{{ user.cn_name }}</td>
                    <td>{{ user.phone }}</td>
                    <td>{{ user.get_sex_display }}</td>
                    <td>
                        {% if user.is_active == 1 %}
                            活跃 <a href="#" class="btn btn-warning btn-xs">禁用</a>
                        {% else %}
                            禁用 <a href="#" class="btn btn-success btn-xs">活跃</a>
                        {% endif %}
                    </td>
                    <td>{% if user.last_login == None %}未登录{% else %} {{ user.last_login }} {% endif %}</td>
                    <td class="actions">
                    <a href="{% url 'users:useredit' user.id %}" class="btn btn-primary btn-xs">编辑</a>
                    <a id="delbtn" userid="{{ user.id }}" class="btn btn-danger btn-xs">删除</a>
                </tr>
                {% endfor %}
                </tbody>
            </table><!--表格 ends-->
        </div> <!-- panel-body ends-->


        <!--分页 start-->
        <div class="row">
            <div class="col-md-4">
               <p style="margin-top: 10px"> 显示 [{{ page_obj.paginator.count }}] 条数据中的 第 [{{ page_obj.start_index }}] 至 [{{ page_obj.end_index }}] 的数据</p>
            </div>
            <div class="col-md-8">
                 {% if page_obj.paginator.num_pages > 1 %}
                    {% include '_paginator.html' %}
                 {% endif %}
            </div>
        </div> <!--分页 ends-->

    </div> <!-- end Panel -->

</div> <!-- End row -->

{% endblock %}

{% block js %}
    <script src="{% static "js/jquery-3.6.0.js"%}"></script>
{#     <script src="{% static "js/sweetalert.min.js"%}"></script>#}
    <script src="{% static "assets/sweet-alert/sweetalert2.min.js"%}"></script>
    <script src="{% static "assets/sweet-alert/sweetalert2.all.min.js"%}"></script>
    <script src="{% static "assets/sweet-alert/sweetalert2.all.js"%}"></script>
    <script src="{% static "assets/sweet-alert/sweetalert2.js"%}"></script>

{#    <script src="{% static "assets/sweet-alert/sweet-alert.min.js"%}"></script>#}
{#    <script src="{% static "assets/sweet-alert/sweet-alert.init.js"%}"></script>#}


    <script>
        // 编辑删除按钮
        $("tbody").on("click","#delbtn", function () {
            var uid = $(this).attr('userid')
            var url = "/user/userdel/" + uid + '/'
            Swal.fire({
                title: "确定删除该用户？",
                text: "删除后可就无法恢复了。",
                icon: "warning",
                showCancelButton: true,
                confirmButtonText: "是的，我要删除！",
                cancelButtonText: "取消",
                cancelButtonColor: '#d33',
                confirmButtonColor: '#3085d6',
            }).then((result) => {
                if (result.isConfirmed) {
                    $.ajax({
                        type: "post",
                        url: url,
                        success: function (res) {
                            console.log(res)
                            if (res.code == 0) {
                                Swal.fire({
                                    title: "删除成功!",
                                    text: "该用户已经删除了.",
                                    icon: "success",
                                    timer: 3000
                                });
                                setTimeout(function () {
                                    window.location.reload();
                                }, 3000)
                            }
                            else {
                                Swal.fire("OMG...", "出错拉", "error");
                            }
                        },
                        error: function () {
                            Swal.fire("OMG...", "接口调用失败!", "error")
                        }
                    })
                }
            })
        })  //$("tbody")


    </script>

<!--
    <script>
        // 编辑删除按钮
    $("tbody").on("click","#delbtn", function () {
        var uid = $(this).attr('userid')
        var url = "/user/userdel/" + uid + '/'
        swal({
            title: "确定删除该用户？",
            text: "删除后可就无法恢复了。",
            icon: "warning",
            showCancelButton: true,
            closeOnConfirm: false,
            confirmButtonText: "是的，我要删除！",
            confirmButtonColor: "",
            cancelButtonColor: '#d33',
            cancelButtonText: "取消"
        }, function (isConfirm) {
            if (!isConfirm) return;
            $.ajax({
                type: "post",
                url: url,
                success: function (res) {
                    console.log(res)
                    if (res.code == 0) {
                        swal.fire({
                            title: "删除成功!",
                            text: "该用户已经删除了.",
                            icon: "success",
                            timer: 3000});
                        {#setTimeout(function () {#}
                        {#        window.location.reload();#}
                        {#    }, 5000);  //单位是毫秒，设置5秒后重新刷新当前页面#}
                    }
                    else {
                        swal("OMG...", "出错拉", "error");
                    }
                },
                error: function () {
                    swal("OMG...", "接口调用失败!", "error");
                }
            })
        });
    })

    </script>
-->

<!-- start

    <script type="text/javascript">
        $("tr").on('click', '#delbtn', function () {
            {#let that = $(this)#}
            {#console.log(that)#}
            {#console.log(that.attr('userid'))#}
            let uid = $(this).attr('userid')
            let url = "/user/userdel/" + uid + '/'


            {#let username = $(this).attr('username')#}
            console.log(uid)
            console.log(url)
            if (confirm("是否确认删除?")){
                $.ajax({
                    url: url,
                    type: 'POST',
                    success: function (res) {
                        console.log(res)
                        if (res.code==0){
                            {#alert("删除成功")#}
                            swal("删除成功!", "You clicked the button!", "success");
                            setTimeout(function () {
                                window.location.reload();
                            }, 150);
                        }
                        else {
                            alert(res.result)
                            {#alert("删除失败")#}
                        }
                    }
                })
            }
        })
    </script>
end comment -->
{% endblock %}