mysite/HTML/urls.py
#!/usr/bin/env python3
#-*- coding:UTF-8 -*-

from django.urls import path
from . import views

app_name = 'HTML'
urlpatterns = [
    path('', views.HtmlView.as_view(), name='html'),
]

mysite/mysite/urls.py
# !/usr/bin/env python3
# -*- coding:UTF-8 -*-


"""mysite URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.2/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from .views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),
    # path('polls/', include('polls.urls')),
    # path('uploads/', include('uploads.urls')),
    # HTML测试
    # path('html/', include('HTML.urls')),

    # 马哥实战测试
    # path('hello/', include('hello.urls')),
    path('user/', include('users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/HTML/models.py
from django.db import models

# Create your models here.

mysite/HTML/views.py
# --*-- coding=utf-8 --*--


from django.shortcuts import render,reverse
from django.views.generic import View,TemplateView
import os

class HtmlView(TemplateView):
    template_name = 'HTML/test.html'
    def post(self, request):
        # print(request.POST)
        # data = request.POST.dict
        # print(data)
        # 方法1：获取多选框的一键多值
        # hobby = request.POST.getlist('hobby', '')
        # 方法2：字典解析式
        data = dict((k, ','.join(v)) for k, v in dict(request.POST).items())
        print(data)
        file = request.FILES.get('file', None)
        if file:
            f = open(os.path.join('mysite/media/images/', file.name), 'wb')
            for line in file.chunks():
                f.write(line)
            f.close()
        return render(request, 'HTML/test.html')

mysite/HTML/templates/HTML/test.html
<!DOCTYPE html>
<html lang="en">
{#头部#}
<head>
    <meta charset="UTF-8">
    <title>html测试页面</title>
</head>
{#正文#}
<body>
    {#标题#}
{#    <h1>This is a heading</h1>#}
{#    <h2>This is a heading</h2>#}
{#    <h3>This is a heading</h3>#}
    {#段落#}
{#    <p>This is a paragraph</p>#}
{#    <p>This is another paragraph</p>#}
    {#超链接#}
{#    <a href="https://www.baidu.com" target="top">百度一下</a>#}
    {#盒子div#}
{#    <div>#}
{#        <div>第一个框</div>#}
{#        <div>第二个框</div>#}
{#    </div>#}
{##}
{#表格#}
{#<table border="1">#}
{#    表头#}
{#    <thead>#}
{#        <tr>#}
{#            <th>姓名</th>#}
{#            <th>年龄</th>#}
{#        </tr>#}
{#    </thead>#}
{#    表的正文#}
{#    <tbody>#}
{#        <tr>#}
{#            <td>张三</td>#}
{#            <td>18</td>#}
{#        </tr>#}
{#        <tr>#}
{#            <td>李四</td>#}
{#            <td>20</td>#}
{#        </tr>#}
{#    </tbody>#}
</table>


<form name="user" method="post" action="{% url "HTML:html" %}" target="_self" enctype="multipart/form-data">
    {% csrf_token %}
    姓名：<input type="text" name="username" value="" placeholder="姓名">
    <br><br>
    密码：<input type="password" name="password" value="" placeholder="密码">
    <br><br>
    性别：<input type="radio" name="sex" value="1" checked>男<input type="radio" name="sex" value="2">女
    <br><br>
    手机：<input type="text" name="phone" value="" placeholder="手机">
    <br><br>
    邮箱：<input type="email" name="email" value="" placeholder="邮箱">
    <br><br>
    跑步 <input type="checkbox" name="hobby" value="sport">
    读书 <input type="checkbox" name="hobby" value="read">
    <br><br>
    技能：
    <select name="skill" size="4" multiple>
        <option value="1" selected>python</option>
        <option value="2">java</option>
        <option value="3">c</option>
        <option value="4">Go</option>
        <option value="5">django</option>
    </select>
    <br><br>
    个人简介:
    <textarea name="introduce" cols="50" rows="5" placeholder="请简短介绍下自己"></textarea>>
    <br><br>
    附件上传:
    <input type="file" name="file">
    <br><br>
    <input type="submit" name="save" value="提交">
    <input type="reset" name="reset" value="重置">
</form>
</body>

<br><br><br><br><br><br><br><br>
<footer>点滴技术©2021</footer>
</html>